### PR TITLE
Fix extension not showing voltages below 1 volt

### LINKED ISSUE #21: The applet ignores all voltage values in mV
Hi,
Thank you for maintaining this applet.
Here is my issue:
First, you can see my `sensors` output, and then the applet output. It seems that every value in mW is missing from the applet.
Capture d’écran de 2019-12-13 18-33-53
Capture d’écran de 2019-12-13 18-34-30

### PR DESCRIPTION
**Pull request by artscoop**
Fixed parsing of sensors voltage lines.
Changed display of voltage values to show three decimals instead of two (to cater for millivolt values).

Fixes #21

### CODE REVIEW

File: utilities.js [hunk 1]
```diff
@@ -172,20 +172,23 @@ function parseFanRPMLine(label, value) {
...
+      sensor['volt'] = parseFloat(matchValue[1]);
+      sensor['min'] = parseFloat(matchValue[3]);
+      sensor['max'] = parseFloat(matchValue[4]);
+      if(matchValue[2] == "mV") {
+      	sensor['volt'] = sensor['volt'] / 1000.0;
+      }
     }
-    return sensor;
+  }
+  return sensor;
```
Comment (HarlemSquirrel) [inline utilities.js]: This project is using 4 spaces for indentation as per GNOME JS style guide

**Review by HarlemSquirrel — CHANGES_REQUESTED** [review]
Sorry, I didn't get notified about this so I just saw it. Thanks for the work here, this looks nice. We just want the indentation to be consistent.

File: utilities.js [hunk 2]
```diff
@@ -172,20 +172,23 @@ function parseFanRPMLine(label, value) {
...
+    // does the current value look like a voltage line?
+    if(matchValue) {
+      sensor = new Array();
+      sensor['label'] = label;
+      sensor['volt'] = parseFloat(matchValue[1]);
+      sensor['min'] = parseFloat(matchValue[3]);
+      sensor['max'] = parseFloat(matchValue[4]);
+      if(matchValue[2] == "mV") {
+      	sensor['volt'] = sensor['volt'] / 1000.0;
+      }
```
Comment (HarlemSquirrel) [inline utilities.js]:
```suggestion
    let sensor = undefined;
    if(label != undefined && value != undefined) {
        const regex = /\s+([\d\.]+)\s+(m?V)\s+\(min\s+\=\s+\+([\d\.]+)\sV,\smax\s\=\s+\+([\d\.]+)/;
        const matchValue = value.match(regex);
        // does the current value look like a voltage line?
        if(matchValue) {
            sensor = new Array();
            sensor['label'] = label;
            sensor['volt'] = parseFloat(matchValue[1]);
            sensor['min'] = parseFloat(matchValue[3]);
            sensor['max'] = parseFloat(matchValue[4]);
            if(matchValue[2] == "mV") {
                sensor['volt'] = sensor['volt'] / 1000.0;
            }
```

File: utilities.js [hunk 3]
```diff
@@ -174,18 +174,21 @@ function parseFanRPMLine(label, value) {
...
+            sensor['volt'] = parseFloat(matchValue[1]);
+            sensor['min'] = parseFloat(matchValue[3]);
+            sensor['max'] = parseFloat(matchValue[4]);
+            if(matchValue[2] == "mV") {
+                sensor['volt'] = sensor['volt'] / 1000.0;
+            }
     }
-    return sensor;
+  }
+  return sensor;
```
Comment (HarlemSquirrel) [inline utilities.js]:
```suggestion
    }
    return sensor;
```

**Review by HarlemSquirrel — APPROVED** [review]
Thanks
